Removes max_id decrement by one for IdIderator.
Since the change to search API 1.1 this seems to be wrong. With decrement by 1
you will get the following error:
tweepy.error.TweepError: [{'message': 'Missing or invalid url parameter', 'code': 195}]

Removing it seems to resolve this without causing duplicates.