Documentation: Added screen_name parameter to get_user method
In Getting started section of the documentation, under Models sub-heading, its mentioned as:
user = api.get_user('twitter')
but it returns the error found below: 
TypeError: get_user() takes 1 positional argument but 2 were given.

So it would be easier for dummies like me, if its mentioned as 
user = api.get_user(screen_name='twitter')
instead.